# Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>, 2015. #zanata
# Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-10-15 09:53+0200\n"
"PO-Revision-Date: 2017-07-01 03:51+0000\n"
"Last-Translator: Ooyama Yosiyuki <qqke6wd9k@apricot.ocn.ne.jp>\n"
"Language-Team: Japanese\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"X-Generator: Zanata 4.6.2\n"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:40
msgid "the color of the sky"
msgstr ""

#: ../plugins/system_upgrade.py:56
msgid "Need a --releasever greater than the current system version."
msgstr "--releasever は、現在のシステムのバージョン番号よりも大きくなければなりません。"

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:58
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf system-upgrade clean'"
msgstr ""

#: ../plugins/system_upgrade.py:61
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""

#: ../plugins/system_upgrade.py:236
msgid "The following boots appear to contain upgrade logs:"
msgstr ""

#: ../plugins/system_upgrade.py:246
msgid "-- no logs were found --"
msgstr ""

#: ../plugins/system_upgrade.py:261
msgid "Cannot find logs with this index."
msgstr ""

#: ../plugins/system_upgrade.py:270
msgid "Unable to match systemd journal entry"
msgstr ""

#: ../plugins/system_upgrade.py:289
msgid "Prepare system for upgrade to a new release"
msgstr "システムに新リリースにアップグレードするための準備をしてください"

#: ../plugins/system_upgrade.py:299
msgid "keep installed packages if the new release's version is older"
msgstr ""

#: ../plugins/system_upgrade.py:303
msgid "which logs to show"
msgstr ""

#: ../plugins/system_upgrade.py:359
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""

#: ../plugins/system_upgrade.py:363
msgid "Operation aborted."
msgstr ""

#: ../plugins/system_upgrade.py:416
msgid "system is not ready for upgrade"
msgstr "システムはアップグレードの準備ができてません。"

#: ../plugins/system_upgrade.py:418
msgid "upgrade is already scheduled"
msgstr "アップグレードは既に予定されています"

#: ../plugins/system_upgrade.py:424
msgid "trigger file does not exist. exiting quietly."
msgstr ""

#: ../plugins/system_upgrade.py:427
msgid "another upgrade tool is running. exiting quietly."
msgstr ""

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:433
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:450
msgid "Rebooting to perform upgrade."
msgstr ""

#: ../plugins/system_upgrade.py:472 ../plugins/system_upgrade.py:478
msgid "Starting system upgrade. This will take a while."
msgstr "system upgrade を起動中。しばらく時間がかかります。"

#: ../plugins/system_upgrade.py:504
#, python-format
msgid "Unable to match package: %s"
msgstr ""

#: ../plugins/system_upgrade.py:509
msgid "Unable to match some of packages"
msgstr ""

#: ../plugins/system_upgrade.py:512
msgid "Cleaning up downloaded data..."
msgstr "ダウンロード済みデータを掃除しています..."

#: ../plugins/system_upgrade.py:550
msgid "Download finished."
msgstr ""

#: ../plugins/system_upgrade.py:554 ../plugins/system_upgrade.py:555
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "アップグレードは完了しました！ 掃除と再起動中..."

#: ../plugins/tracer.py:70
msgid "For more information run:"
msgstr ""

#: ../plugins/tracer.py:97
msgid "Call to Tracer API ended unexpectedly:"
msgstr ""

#: ../plugins/tracer.py:99
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""

#: ../plugins/tracer.py:101
msgid "We apologize for any inconvenience"
msgstr "ご不便をお掛けして申し訳ございません"

#: ../plugins/rpm_conf.py:67
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr ""

#: ../plugins/rpm_conf.py:73
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr ""

#: ../plugins/rpm_conf.py:86
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr ""

#: ../plugins/rpm_conf.py:90
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr ""

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr ""

#: ../plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr ""

#: ../plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr ""

#: ../plugins/snapper.py:71
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr ""

#: ../plugins/snapper.py:77
msgid "creating post_snapshot"
msgstr ""

#: ../plugins/snapper.py:82
#, python-format
msgid "created post_snapshot %d"
msgstr ""

#: ../plugins/snapper.py:86
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr ""

#: ../plugins/kickstart.py:59
msgid "Install packages defined in a kickstart file on your system"
msgstr ""

#: ../plugins/kickstart.py:64
msgid "kickstart file"
msgstr ""

#: ../plugins/kickstart.py:82
#, python-format
msgid "file cannot be parsed: %s"
msgstr "ファイルがパースできません: %s"

#: ../plugins/kickstart.py:99
#, python-format
msgid "No package %s available."
msgstr ""

#: ../plugins/kickstart.py:104
msgid "Nothing to do."
msgstr "行うべき処理がありません。"

#: ../plugins/torproxy.py:32
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""
