# Daniel Lara <danniel@fedoraproject.org>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-11-24 11:34+0100\n"
"PO-Revision-Date: 2016-09-06 08:59-0400\n"
"Last-Translator: Frederico Henrique Gonçalves Lima <fred@fredericolima.com.br>\n"
"Language-Team: Portuguese (Brazil)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt-BR\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 3.9.6\n"

#: ../plugins/repoclosure.py:46
msgid "Display a list of unresolved dependencies for repositories"
msgstr "Exibir uma lista de dependências não resolvidas para os repositórios"

#: ../plugins/repoclosure.py:117
msgid "check packages of the given archs, can be specified multiple times"
msgstr ""

#: ../plugins/repoclosure.py:120
msgid "Specify repositories to check"
msgstr "Especificar repositórios para checagem"

#: ../plugins/repoclosure.py:122
msgid "Check only the newest packages in the repos"
msgstr ""

#: ../plugins/repoclosure.py:125
msgid "Check closure for this package only"
msgstr "Verificar o fechamento somente para este pacote"

#: ../plugins/versionlock.py:32
#, python-format
msgid "Unable to read version lock configuration: %s"
msgstr "Não foi possível ler a configuração de bloqueio de versão: %s"

#: ../plugins/versionlock.py:33
msgid "Locklist not set"
msgstr "Lista de bloqueio não definida"

#: ../plugins/versionlock.py:34
msgid "Adding versionlock on:"
msgstr "Adicionando bloqueio de versão em:"

#: ../plugins/versionlock.py:35
msgid "Adding exclude on:"
msgstr "Adicionando exclusão em:"

#: ../plugins/versionlock.py:36
msgid "Deleting versionlock for:"
msgstr "Removendo bloqueio de versão para:"

#: ../plugins/versionlock.py:37
msgid "No package found for:"
msgstr "Nenhum pacote encontrado para:"

#: ../plugins/versionlock.py:89
msgid "control package version locks"
msgstr "controlar bloqueios de versão de pacotes"

#: ../plugins/migrate.py:57
#, python-format
msgid "failed to parse package NEVRA from: %s"
msgstr "falha ao analisar o pacote NEVRA de: %s"

#: ../plugins/migrate.py:78
msgid "migrate yum's history, group and yumdb data to dnf"
msgstr "migrar o histórico, grupo e dados yumdb do yum para dnf"

#: ../plugins/migrate.py:95
msgid "which kind of yum data migrate."
msgstr "qual tipo de dados do yum migrar."

#: ../plugins/migrate.py:111
msgid "Migrating history data..."
msgstr "Migrando dados de histórico..."

#: ../plugins/migrate.py:222
msgid "Migrating groups data..."
msgstr "Migrando dados de grupos..."

#: ../plugins/migrate.py:227
msgid "Execution of Yum failed. Could not retrieve installed groups."
msgstr "Falha na execução do Yum. Impossível resgatar grupos instalados."

#: ../plugins/migrate.py:231
msgid "No groups to migrate from Yum"
msgstr "Nenhum grupo do Yum para migrar"

#: ../plugins/migrate.py:243
msgid "skipping."
msgstr "pulando."

#: ../plugins/migrate.py:263
msgid "Migrating YUMDB data..."
msgstr "Migrando dados do YUMDB..."

#: ../plugins/migrate.py:282
#, python-format
msgid "%s of %s not found"
msgstr "%s de %s não encontrados"

#: ../plugins/migrate.py:289
#, python-format
msgid "replacing unknown characters in %s of %s"
msgstr "substituindo caracteres desconhecidos em %s de %s"

#: ../plugins/migrate.py:294
msgid "DNFDB access denied"
msgstr "acesso ao DNFDB negado"

#: ../plugins/migrate.py:296
#, python-format
msgid "%s of %s migrated"
msgstr "%s de %s migrados"

#: ../plugins/migrate.py:300
#, python-format
msgid "%d YUMDB records found, %d migrated, %d skipped/preserved"
msgstr ""
"%d registros do YUMDB encontrados, %d migrados, %d pulados/preservados"

#: ../plugins/repograph.py:54
msgid "Output a full package dependency graph in dot format"
msgstr ""
"Saída em um gráfico de dependência completa dos pacotes no formato de ponto "

#: ../plugins/repograph.py:115
#, python-format
msgid "Nothing provides: '%s'"
msgstr "Nada fornece: '%s'"

#: ../plugins/kickstart.py:58
msgid "Install packages defined in a kickstart file on your system"
msgstr ""
"Instalar em seu sistema os pacotes definidos em um arquivo do kickstart"

#: ../plugins/kickstart.py:63
msgid "kickstart file"
msgstr ""

#: ../plugins/kickstart.py:81
#, python-format
msgid "file cannot be parsed: %s"
msgstr "arquivo não pode ser analisado: %s"

#: ../plugins/kickstart.py:98
#, python-format
msgid "No package %s available."
msgstr "Nenhum pacote %s disponível."

#: ../plugins/kickstart.py:103
msgid "Nothing to do."
msgstr "Nada a ser feito."

#: ../plugins/show_leaves.py:56
msgid "New leaves:"
msgstr "Novas folhas:"

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "conexão com o snapperd falhou: %s"

#: ../plugins/snapper.py:54
msgid "creating snapshot"
msgstr "criando snapshot"

#: ../plugins/snapper.py:59
#, python-format
msgid "created snapshot %d"
msgstr "snapshot criado %d"

#: ../plugins/snapper.py:63
#, python-format
msgid "creating snapshot failed: %s"
msgstr "falha ao criar snapshot: %s"

#: ../plugins/repomanage.py:44
msgid "Manage a directory of rpm packages"
msgstr "Gerenciar um diretório de pacotes rpm"

#: ../plugins/repomanage.py:52
msgid "Pass either --old or --new, not both!"
msgstr "Passe --old ou --new, não ambos!"

#: ../plugins/repomanage.py:62
msgid "No files to process"
msgstr "Nenhum arquivo para processar"

#: ../plugins/repomanage.py:67
msgid "Could not open {}"
msgstr "Impossível abrir {}"

#: ../plugins/repomanage.py:124
msgid "Print the older packages"
msgstr "Imprimir os pacotes mais antigos"

#: ../plugins/repomanage.py:126
msgid "Print the newest packages"
msgstr "Imprimir os pacotes mais novos"

#: ../plugins/repomanage.py:128
msgid "Space separated output, not newline"
msgstr "Saída separada por espaço, não por nova linha"

#: ../plugins/repomanage.py:130
msgid "Newest N packages to keep - defaults to 1"
msgstr "Manter N pacotes mais novos - padrão para 1"

#: ../plugins/repomanage.py:133
msgid "Path to directory"
msgstr "Caminho para o diretório"

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""

#: ../plugins/rpm_conf.py:67
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr ""
"Adicionando '{}' para a lista de pacotes de manipulação para o rpmconf"

#: ../plugins/rpm_conf.py:73
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr ""

#: ../plugins/rpm_conf.py:86
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr ""

#: ../plugins/rpm_conf.py:90
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr ""

#: ../plugins/leaves.py:32
msgid "List installed packages not required by any other package"
msgstr "Lista de pacotes instalados não exigidos por nenhum outro pacote"

#: ../plugins/system_upgrade.py:54
msgid "the color of the sky"
msgstr ""

#: ../plugins/system_upgrade.py:73
msgid "No new kernel packages were found."
msgstr ""

#: ../plugins/system_upgrade.py:75
msgid "Need a --releasever greater than the current system version."
msgstr ""

#: ../plugins/system_upgrade.py:77
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade."
msgstr ""

#: ../plugins/system_upgrade.py:79
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""

#: ../plugins/system_upgrade.py:112
msgid "--datadir: File exists"
msgstr ""

#: ../plugins/system_upgrade.py:257
msgid "The following boots appear to contain upgrade logs:"
msgstr ""

#: ../plugins/system_upgrade.py:267
msgid "-- no logs were found --"
msgstr ""

#: ../plugins/system_upgrade.py:282
msgid "Cannot find logs with this index."
msgstr ""

#: ../plugins/system_upgrade.py:305
msgid "Prepare system for upgrade to a new release"
msgstr ""

#: ../plugins/system_upgrade.py:314
msgid "save downloaded data to this location"
msgstr ""

#: ../plugins/system_upgrade.py:317
msgid "keep installed packages if the new release's version is older"
msgstr ""

#: ../plugins/system_upgrade.py:398
msgid "system is not ready for upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:400
msgid "upgrade is already scheduled"
msgstr ""

#: ../plugins/system_upgrade.py:406
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr ""

#: ../plugins/system_upgrade.py:408
msgid "another upgrade tool is running. exiting quietly."
msgstr ""

#: ../plugins/system_upgrade.py:432
msgid "Rebooting to perform upgrade."
msgstr ""

#: ../plugins/system_upgrade.py:459 ../plugins/system_upgrade.py:465
msgid "Starting system upgrade. This will take a while."
msgstr ""

#: ../plugins/system_upgrade.py:496
msgid "Cleaning up downloaded data..."
msgstr ""

#: ../plugins/system_upgrade.py:527
msgid "Download finished."
msgstr ""

#: ../plugins/system_upgrade.py:531 ../plugins/system_upgrade.py:532
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr ""

#: ../plugins/debug.py:55
msgid "dump information about installed rpm packages to file"
msgstr "descarregar para arquivo as informações sobre pacotes rpm instalados"

#: ../plugins/debug.py:69
msgid "do not attempt to dump the repository contents."
msgstr "não tente descarregar o conteúdo do repositório."

#: ../plugins/debug.py:72
msgid "optional name of dump file"
msgstr "nome opcional do arquivo de descarregamento"

#: ../plugins/debug.py:97
#, python-format
msgid "Output written to: %s"
msgstr "Saída escrita para: %s"

#: ../plugins/debug.py:175
msgid "restore packages recorded in debug-dump file"
msgstr "restaurar pacotes gravados no arquivo de depuração-descarregamento"

#: ../plugins/debug.py:186
msgid "output commands that would be run to stdout."
msgstr "Saída em comandos que deveriam ser executados para a saída padrão."

#: ../plugins/debug.py:189
msgid "Install the latest version of recorded packages."
msgstr "Instale as versão mais recentes dos pacotes gravados."

#: ../plugins/debug.py:192
msgid ""
"Ignore architecture and install missing packages matching the name, epoch, "
"version and release."
msgstr ""

#: ../plugins/debug.py:197
msgid "limit to specified type"
msgstr "limite para o tipo especificado"

#: ../plugins/debug.py:199
msgid "name of dump file"
msgstr "nome do arquivo de descarregamento"

#: ../plugins/debug.py:268
#, python-format
msgid "Package %s is not available"
msgstr "Pacote %s indisponível"

#: ../plugins/debug.py:278
#, python-format
msgid "Bad dnf debug file: %s"
msgstr "Arquivo dnf de depuração inválido: %s"

#: ../plugins/local.py:115
msgid "'{}' is not a directory"
msgstr "'{}' não é um diretório"

#: ../plugins/local.py:124
msgid "Copying '{}' to local repo"
msgstr "Copiando '{}' para o repo local"

#: ../plugins/local.py:130
msgid "Can't write file '{}'"
msgstr "Impossível escrever arquivo '{}'"

#: ../plugins/local.py:145
msgid "Rebuilding local repo"
msgstr "Reconstruindo repo local"

#: ../plugins/tracer.py:75
msgid "For more information run:"
msgstr "Para mais informações execute:"

#: ../plugins/tracer.py:102
msgid "Call to Tracer API ended unexpectedly:"
msgstr ""

#: ../plugins/tracer.py:104
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""

#: ../plugins/tracer.py:106
msgid "We apologize for any inconvenience"
msgstr "Nos desculpamos por qualquer inconveniência"
